set foreign_key_checks=0;
DROP TABLE IF EXISTS poolform_poolbench;
DROP TABLE IF EXISTS formgroup_poolbench;
DROP TABLE IF EXISTS formgroup_stepsform;
DROP TABLE IF EXISTS formgroups;
DROP TABLE IF EXISTS poolform_stepsform;
DROP TABLE IF EXISTS poolforms;
DROP TABLE IF EXISTS formtypes;
DROP TABLE IF EXISTS ledremotes;
DROP TABLE IF EXISTS technicsboxchanges;
DROP TABLE IF EXISTS poolframecolors;
DROP TABLE IF EXISTS poolcolors;
DROP TABLE IF EXISTS pooltype_gsa;
DROP TABLE IF EXISTS gsas;
DROP TABLE IF EXISTS leds;
DROP TABLE IF EXISTS poolwater_ventil;
DROP TABLE IF EXISTS ventils;
DROP TABLE IF EXISTS whirlpools;
DROP TABLE IF EXISTS electros;
DROP TABLE IF EXISTS poolwaters;
DROP TABLE IF EXISTS pooltype_technicsbox;
DROP TABLE IF EXISTS technicsboxes;
DROP TABLE IF EXISTS skimmertypes;
DROP TABLE IF EXISTS poolbenches;
DROP TABLE IF EXISTS pooltype_poolframe;
DROP TABLE IF EXISTS colorvaris;
DROP TABLE IF EXISTS stepsforms;
DROP TABLE IF EXISTS poolframes;
DROP TABLE IF EXISTS pooledges;
DROP TABLE IF EXISTS sizechanges;
DROP TABLE IF EXISTS confs;
DROP TABLE IF EXISTS pooltypes;
DROP TABLE IF EXISTS pooltechnics;
DROP TABLE IF EXISTS poolsizes;
set foreign_key_checks=1;

